language: node_js
node_js:
  - node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: SKpX9kbYS0OUMgrSrBOyccd+Pun6E5dImPODkdYZPkTkZ658mvTjxWuTpGaB4VVhLcLO5NACvdxhfKngcb7gcdpJfja0TAvCCRKbUi55pc9zm0Dg/cxum/+gncxPnpa/1qEc48MFC3FzfrDSmGR9sAGGCQlqezrkLQAFBUnj8UfjhL0H4PCBOIjdho4sK7kMhZ1ZvjRhG/2pX0L+sAWZgLgvLffD5mdZb+X+Kwh1O+zQjJTFCwQyRLwWlrCB093KCRaPg9Y10S3XjvRCRD4PWwp+KHI2lZPcyvvtTMpnRqgfmcixMXshZE4lTGMfgNdFzwhMntvWgTHmewkudjrwkAqFVPvZ2jiyxQXwLeYp4qDcnbzEtdykInFPFkGk245/6ARgAfS0zWIPQRFiXVU5SgSVpbn8g5C9wMcZ9AaVf2XvnOWKG6HK3Q21iwN2QvBvjishUrmQ+Tr1Ke2zdW/C3lQhdbbt9IqSTVZUWevIS4DlxNcq2WpJa30XkA70z6wjddIt8ZruS67vaCmSAznAyLSIKnqtro8rBUGDqUt5PpJJMDN6xFHXGJqt5bx9avS1UGriQ/89p0nF1t+XkJ6uUm8FO6nzF9IAc04BhZ/dC7PtDegSgy4BDiCwpjw7c+PpVFKb1GEnXqfi6y1t8xPefByHERG7ixhKqwrUqmhj1GE=
    app: woord
    skip_cleanup: true
