language: node_js
node_js:
  - node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: C45ZJpvrF7et09PueJSu6mRM0yr9N5YM8Nf+9x1Nfr/suEg47cdbwEbaODmF/pQpyaZ8j75V/9HdyHZVpuGMNWcrAyETLA3IjqoLxBcM+urYuyoIgYsMIl493516OA2YGzt8RUF9FtOXQIJgdK9xwCu11DjuiG6FceyvDQfLzwq+rFL/IRWZvZfsINH2EbfsG5zWR1BLzsJRVaOSPHnCzwipmvxzDIO8FIlhUDMDtX0a7mNgV/IQSj9YQyADLMhCcmXtpmJ5j+15k6rb+7kbdGtWMWrg1aDGJGYTHHTkAxemUpjGNCKqGa7C7iajWpKvXXsN2MtdHqZt6Hyw8BpIHgkv8AqKHVNCCSZwMRj5f5tbLxbyQ5uAsgxsQS51pUm8jvu7Od5k3Ll0DM3sQwUqJ15axtg2ob5VmknG+LeZGLCym1AVtmQJvWUNqPHN3WyQ4f/iAi9Lnki5BkUpmp1pjcukaqWi8xRJYjviByn7qGuMwX+HJZ8J1E5G0HU9fv592MeZ9DOZbRPlIrEdfTn9mwlKNLQaXUBErWOBF+D3zOKQ3pW5i0zhTowG3XnTakpzcwjIWJlMUItpZ+EM+iLmEQtSpk/TuDApLx0C5/4lS+iRG+A5uXfmnSCtMPHjIfM6RZf8EhCFdaFORlAnZt9E7qYSK/GhNKYaRGbhjcZZ1xs=
    app: woord
    skip_cleanup: true
